### PR TITLE
Fix the flashing of dashboard before onboarding modal

### LINKED ISSUE #6403: The library is shown before the onboarding modal
STR:
1. Open replay as a new user
2. notice how the library flashes momentarily

This is fairly easy to reproduce by updating the IF statement in the effect to be true

https://app.replay.io/recording/initial-load--638d7723-e238-4574-a519-3944178ac9e4?point=6814889628629178182488377983500923&time=2694.537017205683&hasFrames=true

### PR DESCRIPTION
**Pull request by ashwinkhode**
Fixes #6403 

**Replay before fix** - https://app.replay.io/recording/initial-load--638d7723-e238-4574-a519-3944178ac9e4?point=6814889628629178182488377983500923&time=2694.537017205683&hasFrames=true
**Loom Video before fix** - https://www.loom.com/share/00f32b5463774270bf8e9f790091a4ae

**Loom Video after fix** - https://www.loom.com/share/622739417d9045fbac5aba23bdee810e

I tested the fix by changing the nags manually. Seems to be working fine. Please let me know if I missed something related to this issue, I would love to do that :)

### CODE REVIEW

**Comment by jasonLaster** [comment]
@ashwinkhode might be fun to include a replay of the bug and fix. This way we can see how adjusting the components fixes the issue

File: packages/accordion/website/pages/_app.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
-import '../styles/globals.css'
+import "../styles/globals.css";
 
 function MyApp({ Component, pageProps }) {
-  return <Component {...pageProps} />
+  return <Component {...pageProps} />;
 }
 
-export default MyApp
+export default MyApp;
```
Comment (jasonLaster) [inline packages/accordion/website/pages/_app.js:7]: might be nice to move these prettier changes to their own PR

File: src/ui/components/Library/Library.tsx [hunk 2]
```diff
@@ -41,46 +41,58 @@ function isUnknownWorkspaceId(
...
+      trackEvent("onboarding.team_invite");
+      setModal("single-invite");
+    } else if (downloadReplay(nags, dismissNag)) {
+      trackEvent("onboarding.download_replay_prompt");
+      setModal("download-replay");
+    } else if (firstReplay(nags)) {
+      trackEvent("onboarding.demo_replay_prompt");
+      setModal("first-replay");
+    }
+  }, []); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (jasonLaster) [inline src/ui/components/Library/Library.tsx:71]: looks cleaner, but how does this fix it?

File: packages/accordion/website/pages/_app.js (hunk 1 above)
Comment (ashwinkhode) [reply packages/accordion/website/pages/_app.js:7]: I think if i dont include this [lint fix commit f2f941f](https://github.com/replayio/devtools/pull/7100/commits/f2f941f66f0991929e752b6198d5595217fb0eac), Lint / Trunk check GH action will fail for this PR :(

File: src/ui/components/Library/Library.tsx (hunk 2 above)
Comment (ashwinkhode) [reply src/ui/components/Library/Library.tsx:71]: Our onboarding modal logic is executed when dashboard is mounted. I just lifted that logic by one level because we have all the data required available to us in `<LibraryLoader />` component. So as soon as we get the user info, we run the onboarding modal logic in the `<LibraryLoader />` component, previously it was getting executed in `<Library />` component. Does this answer your question? Please correct me if I am wrong anywhere 🤔

**Comment by ashwinkhode** [comment]
> @ashwinkhode might be fun to include a replay of the bug and fix. This way we can see how adjusting the components fixes the issue

Hey Jason, I added the replay that was posted in the original issue and also I added my own Loom video recordings for before and after the fix. You can find it in the PR description :)

File: packages/accordion/website/pages/_app.js (hunk 1 above)
Comment (souporserious) [reply packages/accordion/website/pages/_app.js:7]: Appreciate your help here! Sorry about our linting, it is a little wonky right now. If you can remove the lint fix commit and keep these changes isolated to the one file I'll get this merged. We can take a look at linting in a follow-up PR and should probably find a time to run it across the whole codebase anyways.

Comment (ashwinkhode) [reply packages/accordion/website/pages/_app.js]: @souporserious removed the lint fix commit. Please have a look 🙈

**Review by souporserious — APPROVED** [review]
This loads much better now ✨. We appreciate your help fixing this, thank you!
